### ISSUE TITLE
pots left behind in case job is dying

### ISSUE THREAD

**Issue by grembo** [bsdpot/nomad-pot-driver#19]
In case the process of a pot dies (e.g. `killall nginx`) the task is restarted automatically by nomad as expected, but the pot is left behind (`pot list`). When doing a graceful stop of a job (`nomad stop job`) this isn't the case.

**Comment by pizzamig** [comment]
There is already a workaround for this, even if not fully documented.
The `pot`s left behind can be automatically destroyed via `pot prune`. nomad launched `pot` are marked as prunable, meaning that, once stopped, they can be removed.
In `minipot` there is a cronjob to run `pot prune` periodically

**Comment by grembo** [comment]
> There is already a workaround for this, even if not fully documented.
> The `pot`s left behind can be automatically destroyed via `pot prune`. nomad launched `pot` are marked as prunable, meaning that, once stopped, they can be removed.
> In `minipot` there is a cronjob to run `pot prune` periodically

Is the pot marked prunable before or after launch? I'm wondering if there is a possibility for bad timing leading to accidental destruction of a pot that is in the middle of getting provisioned if `pot prune` is run from cron.

**Comment by pizzamig** [comment]
The mechanism is implemented in 2 steps to avoid the situation you described.
There are 2 attributes: prunable and to-be-pruned.
The attribute prunable can be set by the user and automatically set by `pot prepare` (this command has been designed to interact with nomad).
The attribute to-be-pruned is set by `pot start` if prunable is true.
`pot prune` will remove `pot`s that are not running and that have the attribute `prunable`and `to-be-pruned` set to true.

**Comment by grembo** [comment]
It might make sense to integrate this feature into the pot driver (maybe configurable?).

**Comment by pizzamig** [comment]
There is a garbage collection feature in nomad and the idea is to run `pot prune` in that moment.
It's currently not working and we need to investigate the cause.
An alternative idea is to run `pot prune` after the pot is stopped.

**Comment by grembo** [comment]
@pizzamig I think the changes in pizzamig/pot#200 and trivago/nomad-pot-driver#30 might actually solve this one as well.

**Comment by einsiedlerkrebs** [comment]
I am experiencing the issue, that the pots are not cleaned up after hard reboot of a nomad node. When the system is up again, the zfs filesystems are not mounted into position, therefore the configuration file of a pot can not be found. This leads to a failing prune command and therefore to the inability to run "prepare" in nomad. Because of this reason the node in not reboot safe.

**Comment by grembo** [comment]
I think this has been overcome by events
