### ISSUE TITLE
Permission denied in jails created by nomad

### ISSUE THREAD

**Issue by pizzamig** [bsdpot/nomad-pot-driver#34]
Using a recent FreeBSD (13.1 or newer), processes that uses less privileged users doesn't work as expected.

Create a pot via nomad (`nginx` for instance).
Then, through `pot term`, open a terminal as root an run this command:
```
:/ # su -m www -c ls
su: /bin/csh: Permission denied
```

If I manually create a pot using the same commands (`pot clone`) (same pot image):
```
:/ # su -m www -c ls
COPYRIGHT	etc		media		rescue		tmp
bin		home		mnt		root		usr
boot		lib		net		sbin		var
dev		libexec		proc		sys
```

I've tried to start nomad manually, to rule out changes in `daemon` or in `rc` scripts, and it doesn't work either.

This permission issue prevent `nginx` to work, because it cannot access the file system.

Any idea?

**Comment by pizzamig** [comment]
I was able to reproduce the issue without nomad. It seems it's more related to the export/import flow.

Keeping this open,just in case

**Comment by grembo** [comment]
I think we can close this now (fixed in pot)
