### ISSUE TITLE
prune fails because of unmounted datasets

### ISSUE THREAD

**Issue by einsiedlerkrebs** [bsdpot/nomad-pot-driver#35]
I am experiencing the issue, that the pots are not cleaned up after hard reboot of a nomad node and therefore the jobs are failing.

When the system is up again, the ZFS datasets are not mounted into position, therefore the configuration file of a pot can not be found. 
This leads to a failing prune command and therefore to the inability to run "prepare" in nomad. Because of this reason the node in not reboot safe.  

To reproduce: 
* on a single server nomad node with running services (via pot) run `reboot` command
* after system is up, observe that the desired services are not up

* get pot datasets with `zfs list`
* mount each "service" related datasets and its recursive ones
* run `pot prune`
* trigger fresh service start on nomad node (either setting count to 0 and back to 1 or removing database)
* now service should be working again

**Comment by grembo** [comment]
Thanks for opening this issue.

What does your system config look like, at least:

```
cat /etc/rc.conf
zpool status
```

(after reboot - redact as necessary)

**Comment by einsiedlerkrebs** [comment]
Yes indeed this solved the issue. Thanks.
