### ISSUE TITLE
[QUESTION] is it possible to force nomad client to run pot's set-env on created pots?

### ISSUE THREAD

**Issue by OneOfTheJohns** [bsdpot/nomad-pot-driver#46]
Hi,

I have pot image with tomcat and java application configured inside. For this java application i have to configure some parameters, those parameters might change for each pot instance. I use terraform to run Nomad with pot images via `nomad_job` resource.

Where, and how i might force Nomad client to setup env variables inside of the created/requested pots? There also should be some kind of work around... but no luck of finding it for now from my side.

Thanks.

**Comment by grembo** [comment]
Hm, I might not understand your question correctly - doesn't the env stanza do exactly that?

**Comment by OneOfTheJohns** [comment]
Ah... my bad, for some reason haven't looked into the nomad `job` parameters, it is possible to define it there.
